### ISSUE TITLE
edit web menu

### ISSUE THREAD

**Issue by infchem** [LinuCC/BaBeSK#62]
Remove "Startseite". "BaBeSK" is linked to it already.
The amount of "Guthaben" is displayed twice. Ok?

![babesk_web_menu](https://cloud.githubusercontent.com/assets/10480556/7219054/5940e58e-e68e-11e4-9f48-dd1809b6b929.png)

**Comment by LinuCC** [comment]
Whoops the Guthaben-part was a merge-mistake by me.
Do you think the average DAU will know that "BaBeSK" links to the front page and does not need "Startseite"?

**Comment by infchem** [comment]
yes, he has to...
