### ISSUE TITLE
edit mobile view of web menu

### ISSUE THREAD

**Issue by infchem** [LinuCC/BaBeSK#63]
Remove "Startseite" and the credit in €, it's in the menu already.
Remove the sandwich icon for the menu and use the username instead, like in the normal desktop view.

![screenshot_2015-04-19-08-15-03](https://cloud.githubusercontent.com/assets/10480556/7219057/6fcceeec-e68e-11e4-93a1-f9e59e03f030.png)

**Comment by LinuCC** [comment]
Result of the same bug as #62. Lets continue there.
Added Issue #64 for Sandwich.
